# Generated by Django 3.0.7 on 2020-08-05 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='Phone2',
        ),
        migrations.RemoveField(
            model_name='register',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='register',
            name='district',
        ),
        migrations.RemoveField(
            model_name='register',
            name='mname',
        ),
        migrations.RemoveField(
            model_name='register',
            name='state',
        ),
    ]
