# Generated by Django 3.0.7 on 2020-08-05 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('mname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('Phone1', models.CharField(max_length=15)),
                ('Phone2', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('pin', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=10)),
                ('course', models.CharField(max_length=15)),
                ('year', models.CharField(max_length=10)),
                ('branch', models.CharField(max_length=50)),
                ('comment', models.CharField(max_length=300)),
            ],
        ),
    ]
